<fieldset>
    <legend>Example</legend>
    <table class="table">
        <thead>
        <tr>
            <th>street_id</th>
            <th>district_id</th>
            <th>range_start</th>
            <th>range_end</th>
            <th>range_parity</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>587965</td>
            <td>K42</td>
            <td>1</td>
            <td>9999</td>
            <td>odd-even</td>
        </tr>
        <tr>
            <td>974981</td>
            <td>L42</td>
            <td>1</td>
            <td>9999</td>
            <td>odd</td>
        </tr>
        <tr>
            <td>784521</td>
            <td>W21</td>
            <td>1</td>
            <td>9999</td>
            <td>even</td>
        </tr>
        </tbody>
    </table>
</fieldset>