<fieldset>
    <legend>Example</legend>
    <table class="table">
        <thead>
        <tr>
            <th>islp</th>
            <th>title</th>
            <th>postcode</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>L00001</td>
            <td>Bondgenotenlaan</td>
            <td>3000</td>
        </tr>
        <tr>
            <td>L00024</td>
            <td>Bosberg</td>
            <td>3010</td>
        </tr>
        <tr>
            <td>L00087</td>
            <td>Brusselsestraat</td>
            <td>3020</td>
        </tr>
        </tbody>
    </table>
</fieldset>