<fieldset>
    <legend>Example</legend>
    <table class="table">
        <thead>
        <tr>
            <th>districts_district_id</th>
            <th>districts_officer_id</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>K42</td>
            <td>441234567</td>
        </tr>
        <tr>
            <td>L42</td>
            <td>441234567</td>
        </tr>
        <tr>
            <td>W21</td>
            <td>441234567</td>
        </tr>
        </tbody>
    </table>
</fieldset>