<table class="table">
    <thead>
    <tr>
        <th>id</th>
        <th>title</th>
        <th>postcode</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>587965</td>
        <td>Bondgenotenlaan</td>
        <td>3000</td>
    </tr>
    <tr>
        <td>974981</td>
        <td>Bosberg</td>
        <td>3000</td>
    </tr>
    <tr>
        <td>784521</td>
        <td>Brusselsestraat</td>
        <td>3000</td>
    </tr>
    </tbody>
</table>