<?php
use MyPhpmig\Police\Migration;

class CRABSupport extends Migration
{
    public function up()
    {
        $this->getZones()->set(array('data' => 'Data'));

        $this->_queries = <<<EOL
ALTER TABLE `streets_cities` ADD `crab_city_id` INT(11) NOT NULL DEFAULT 0 AFTER `police_zone_id`;

CREATE TABLE `streets_logs` (
  `streets_log_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('city', 'street'),
  `action` enum('add', 'delete', 'edit'),
  `row` int(5) DEFAULT NULL,
  `name` varchar(160) DEFAULT NULL,
  `fields` TEXT DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  PRIMARY KEY (`streets_log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'Logs the actions generated by syncing with CRAB database';

ALTER TABLE `streets` CHANGE `title0` `title3` VARCHAR(80)  CHARACTER SET utf8  NULL  DEFAULT NULL;
ALTER TABLE `streets` CHANGE `language1` `language` VARCHAR(2)  CHARACTER SET utf8  NULL  DEFAULT NULL;
ALTER TABLE `streets` MODIFY COLUMN `language` VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL AFTER `streets_city_id`;
ALTER TABLE `streets` MODIFY COLUMN `language2` VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL AFTER `slug`;

EOL;

        parent::up();
    }

    public function down()
    {
        $this->getZones()->set(array('data' => 'Data'));

        $this->_queries = <<<EOL
ALTER TABLE `streets_cities` DROP `crab_city_id`;

DROP TABLE `streets_logs`;

ALTER TABLE `streets` CHANGE `title3` `title0` VARCHAR(80)  CHARACTER SET utf8  NULL  DEFAULT NULL;
ALTER TABLE `streets` CHANGE `language` `language1` VARCHAR(2)  CHARACTER SET utf8  NULL  DEFAULT NULL;
ALTER TABLE `streets` MODIFY COLUMN `language2` VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL AFTER `title2`;
ALTER TABLE `streets` MODIFY COLUMN `language1` VARCHAR(2) CHARACTER SET utf8 DEFAULT NULL AFTER `title2`;
EOL;

        parent::down();
    }
}
