location ~ "^/(la-mazerine|lahulpe|lamazerine|lasne|mazerine|rixensart)(?:/.*)?$" {
	rewrite ^ /5269 permanent;
}

location ~ "^/(anthisnes|clavier|comblain-au-pont|condroz|ferrieres|hamoir|marchin|modave|nandrin|ouffet|tinlot)(?:/.*)?$" {
	rewrite ^ /5296 permanent;
}

location ~ "^/(eghezee|gembloux|labruyere|orneau-mehaigne)(?:/.*)?$" {
	rewrite ^ /5304 permanent;
}

location ~ "^/(ciney|condroz-famenne|hamois|havelange|somme-leuze)(?:/.*)?$" {
	rewrite ^ /5314 permanent;
}

location ~ "^/(cerfontaine|doische|philippeville)(?:/.*)?$" {
	rewrite ^ /5315 permanent;
}

location ~ "^/(lalouviere|loupol)(?:/.*)?$" {
	rewrite ^ /5325 permanent;
}

location ~ "^/charleroi(?:/.*)?$" {
	rewrite ^ /5330 permanent;
}

location ~ "^/(beaumont|botha|botte-du-hainaut|botteduhainaut|chimay|froidchapelle|momignies|police-botha|policebotha|rance|sivry|sivry-rance)(?:/.*)?$" {
	rewrite ^ /5334 permanent;
}

location ~ "^/(berchem-sainte-agathe|brussel-west|brussel.west|brusselwest|bruxelles-ouest|bruxelles.ouest|bruxellesouest|ganshoren|jette|koekelberg|molenbeek-saint-jean|sint-agatha-berchem|sint-jans-molenbeek)(?:/.*)?$" {
	rewrite ^ /5340 permanent;
}

location ~ "^/(anderlecht|forest|midi|polbrumidi|saint-gilles|sint-gillis|vorst|zuid)(?:/.*)?$" {
	rewrite ^ /5341 permanent;
}

location ~ "^/(boechout|borsbeek|minos|mortsel|wijnegem|wommelgem)(?:/.*)?$" {
	rewrite ^ /5351 permanent;
}

location ~ "^/mechelen(?:/.*)?$" {
	rewrite ^ /5358 permanent;
}

location ~ "^/(bodukap|bonheiden|duffel|putte|sint-katelijne-waver)(?:/.*)?$" {
	rewrite ^ /5359 permanent;
}

location ~ "^/lier(?:/.*)?$" {
	rewrite ^ /5360 permanent;
}

location ~ "^/(berlaar|nijlen|berlaar-nijlen)(?:/.*)?$" {
	rewrite ^ /5361 permanent;
}

location ~ "^/(heist|heist-op-den-berg)(?:/.*)?$" {
	rewrite ^ /5362 permanent;
}

location ~ "^/(herselt|hulshout|westerlo|zuiderkempen)(?:/.*)?$" {
	rewrite ^ /5365 permanent;
}

location ~ "^/(balen|balen-dessel-mol|dessel|mol)(?:/.*)?$" {
	rewrite ^ /5368 permanent;
}

location ~ "^/lommel(?:/.*)?$" {
	rewrite ^ /5371 permanent;
}

location ~ "^/(achel|hamont|hamont-achel|hano|neerpelt|overpelt)(?:/.*)?$" {
	rewrite ^ /5372 permanent;
}

location ~ "^/(eksel|hechtel|hechtel-eksel|kempenland|leopoldsburg|peer|politiekempenland)(?:/.*)?$" {
	rewrite ^ /5377 permanent;
}

location ~ "^/(helchteren|houthalen|houthalen-helchteren)(?:/.*)?$" {
	rewrite ^ /5378 permanent;
}

location ~ "^/(alken|borgloon|heers|kortessem|pzloon|wellen)(?:/.*)?$" {
	rewrite ^ /5379 permanent;
}

location ~ "^/(ambiorix|herstappe|tongeren|tongeren-herstappe|tongerenherstappe)(?:/.*)?$" {
	rewrite ^ /5380 permanent;
}

location ~ "^/leuven(?:/.*)?$" {
	rewrite ^ /5388 permanent;
}

location ~ "^/(hoegaarden|politiezonetienen-hoegaarden|politiezonetienenhoegaarden|pztienen-hoegaarden|pztienenhoegaarden|tienen|tienen-hoegaarden|tienenhoegaarden)(?:/.*)?$" {
	rewrite ^ /5392 permanent;
}

location ~ "^/aarschot(?:/.*)?$" {
	rewrite ^ /5394 permanent;
}

location ~ "^/(boortmeerbeek|haacht|keerbergen)(?:/.*)?$" {
	rewrite ^ /5395 permanent;
}

location ~ "^/(demerdal|demerdal-dsz|diest|dsz|scherpenheuvel|scherpenheuvel-zichem|zichem)(?:/.*)?$" {
	rewrite ^ /5396 permanent;
}

location ~ "^/(begijnendijk|brt|rotselaar|tremelo)(?:/.*)?$" {
	rewrite ^ /5399 permanent;
}

location ~ "^/zaventem(?:/.*)?$" {
	rewrite ^ /5400 permanent;
}

location ~ "^/(kraainem|wezembeek-oppem|wokra)(?:/.*)?$" {
	rewrite ^ /5401 permanent;
}

location ~ "^/(druivenstreek|hoeilaart|overijse)(?:/.*)?$" {
	rewrite ^ /5402 permanent;
}

location ~ "^/(bever|galmaarden|gooik|herne|lennik|pajottenland|pepingen|politie-pajottenland|politiepajottenland)(?:/.*)?$" {
	rewrite ^ /5405 permanent;
}

location ~ "^/(amow|asse|merchtem|opwijk|wemmel)(?:/.*)?$" {
	rewrite ^ /5408 permanent;
}

location ~ "^/(k-l-m|kapelle-op-den-bos|klm|londerzeel|meise)(?:/.*)?$" {
	rewrite ^ /5409 permanent;
}

location ~ "^/(grimbergen|politiegrimbergen)(?:/.*)?$" {
	rewrite ^ /5410 permanent;
}

location ~ "^/(sint-pieters-leeuw|sintpietersleeuw)(?:/.*)?$" {
	rewrite ^ /5414 permanent;
}

location ~ "^/(gent|politiegent)(?:/.*)?$" {
	rewrite ^ /5415 permanent;
}

location ~ "^/(assenede|assenede-evergem|evergem)(?:/.*)?$" {
	rewrite ^ /5421 permanent;
}

location ~ "^/maldegem(?:/.*)?$" {
	rewrite ^ /5424 permanent;
}

location ~ "^/(brakel|horebeke|maarkedal|zwalm)(?:/.*)?$" {
	rewrite ^ /5426 permanent;
}

location ~ "^/(geraardsbergen|geraardsbergen-lierde|geraardsbergenlierde|lierde|politiegeraardsbergenlierde)(?:/.*)?$" {
	rewrite ^ /5428 permanent;
}

location ~ "^/(herzele|sint-lievens-houtem|zottegem)(?:/.*)?$" {
	rewrite ^ /5429 permanent;
}

location ~ "^/(sint-gillis-waas|sintgilliswaas|stekene)(?:/.*)?$" {
	rewrite ^ /5431 permanent;
}

location ~ "^/(berlare|berlare-zele|overmere|uitbergen|zele)(?:/.*)?$" {
	rewrite ^ /5436 permanent;
}

location ~ "^/(laarne|wetteren|wichelen)(?:/.*)?$" {
	rewrite ^ /5438 permanent;
}

location ~ "^/(aaltert|denderleeuw|haaltert)(?:/.*)?$" {
	rewrite ^ /5439 permanent;
}

location ~ "^/(5442)(?:/.*)?$" {
	rewrite ^ http://users.skynet.be/politieninove permanent;
}

location ~ "^/brugge(?:/.*)?$" {
	rewrite ^ /5444 permanent;
}

location ~ "^/(blankenberge|zuienkerke)(?:/.*)?$" {
	rewrite ^ /5445 permanent;
}

location ~ "^/middelkerke(?:/.*)?$" {
	rewrite ^ /5451 permanent;
}

location ~ "^/(alveringem|lo-reninge|spoorkin|veurne)(?:/.*)?$" {
	rewrite ^ /5459 permanent;
}

location ~ "^/(depanne|koksijde|nieuwpoort|politiewestkust|westkust)(?:/.*)?$" {
	rewrite ^ /5461 permanent;
}

location ~ "^/aalst(?:/.*)?$" {
	rewrite ^ /5440 permanent;
}

location ~ "^/(5423|aalter|knesselare)(?:/.*)?$" {
	rewrite ^ http://users.skynet.be/pzaalter permanent;
}

location ~ "^/(5349|aartselaar|edegem|hekla|hove|kontich|lint)(?:/.*)?$" {
	rewrite ^ http://www.hekla.be permanent;
}

location ~ "^/(5407|affligem|liedekerke|roosdaal|tarl|ternat)(?:/.*)?$" {
	rewrite ^ http://www.tarl.be permanent;
}

location ~ "^/(5331|aiseau|aiseau-presles|chatelet|farciennes|presles)(?:/.*)?$" {
	rewrite ^ http://www.policechatelet.be/ permanent;
}

location ~ "^/(5294|amay|engis|saint-georges-sur-meuse|verlaine|villers-le-bouillet|wanze)(?:/.*)?$" {
	rewrite ^ http://www.zpmeusehesbaye.be/index.asp permanent;
}

location ~ "^/(5291|ambleve|bullange|burg-reuland|butgenbach|eifel|saint-vith)(?:/.*)?$" {
	rewrite ^ http://www.eifelpolizei.be/ permanent;
}

location ~ "^/(5305|andenne|arches|assesse|fernelmont|gesves|ohey)(?:/.*)?$" {
	rewrite ^ http://www.policedesarches.be/ permanent;
}

location ~ "^/(5332|anderlues|binche)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/hai/5332.htm permanent;
}

location ~ "^/(5312|anhee|dinant|hastiere|haute-meuse|onhaye|yvoir)(?:/.*)?$" {
	rewrite ^ http://users.skynet.be/hautemeuse/index.htm permanent;
}

location ~ "^/(5284|ans|saint-nicolas|saintnicolas|stnicolas|zpans-stnicolas)(?:/.*)?$" {
	rewrite ^ http://users.teledisnet.be/web/pbu09115/index.htm redirect;
}

location ~ "^/(5316|antoing|brunehaut|rumes|tournai|tournaisis)(?:/.*)?$" {
	rewrite ^ http://www.policetournaisis.be/ permanent;
}

location ~ "^/(5345|antwerpen)(?:/.*)?$" {
	rewrite ^ http://politie.antwerpen.be permanent;
}

location ~ "^/(5272|ardennes-brabanconnes|ardennesbrabanconnes|beauvechain|chaumont|chaumont-gistoux|gistoux|grez|grez-doiceau|incourt)(?:/.*)?$" {
	rewrite ^ http://users.swing.be/sw368131 permanent;
}

location ~ "^/(ardooie|lichtervelde|pittem|pzregiotielt|ruiselede|tielt|wingene)(?:/.*)?$" {
	rewrite ^ /5448 permanent;
}

location ~ "^/(arendonk|kempen-n-o|kempen-noord-oost|ravels|retie)(?:/.*)?$" {
	rewrite ^ /5367 permanent;
}

location ~ "^/(5297|arlon|attert|habay|martelange)(?:/.*)?$" {
	rewrite ^ http://www.police-arlon.be permanent;
}

location ~ "^/(5462|arro-ieper|arro.ieper|arroieper|heuvelland|ieper|langemark|langemark-poelkapelle|mesen|moorslede|poelkapelle|poperinge|staden|vleteren|wervik|zonnebeke)(?:/.*)?$" {
	rewrite ^ http://www.arroieper.be permanent;
}

location ~ "^/(as|gaoz|genk|opglabbeek|zutendaal)(?:/.*)?$" {
	rewrite ^ /5384 permanent;
}

location ~ "^/(assent|bekkevoort|geetbets|glabbeek|hageland|kortenaken|tielt-winge)(?:/.*)?$" {
	rewrite ^ /5389 permanent;
}

location ~ "^/(5322|ath|villedath)(?:/.*)?$" {
	rewrite ^ http://www.police.ath.be permanent;
}

location ~ "^/(aubange|messancy|musson|saint-leger|sud-luxembourg)(?:/.*)?$" {
	rewrite ^ /5298 permanent;
}

location ~ "^/(aubel|baelen|herve|limbourg|olne|pays-de-herve|paysdeherve|plombieres|thimister-clermont|welkenraedt)(?:/.*)?$" {
	rewrite ^ /5288 permanent;
}

location ~ "^/(auderghem|marlow|oudergem|uccle|uccle-watermael-boitsfort-auderghem|ukkel|ukkel-watermaal-bosvoorde-oudergem|uwa|uwo|watermaal-bosvoorde|watermael-boitsfort)/?$" {
	rewrite ^ /5342 permanent;
}

location ~ "^/(5285|awans|grace-hollogne)(?:/.*)?$" {
	rewrite ^ http://www.grace-hollogne-awans.be/060821141654/index.asp permanent;
}

location ~ "^/(5283|aywaille|chaudfontaine|esneux|secova|sprimont|trooz)(?:/.*)?$" {
	rewrite ^ http://www.secova.be permanent;
}

location ~ "^/(5364|baarle-hertog|beerse|kasterlee|lille|oud-turnhout|politieregioturnhout|turnhout|vosselaar)(?:/.*)?$" {
	rewrite ^ http://www.politieregioturnhout.be permanent;
}

location ~ "^/(basse-meuse|bassemeuse|bassenge|blegny|dalhem|juprelle|oupeye|vise)(?:/.*)?$" {
	rewrite ^ /5281 permanent;
}

location ~ "^/(5301|bastogne|bertogne|centre-ardenne|chevigny|fauvillers|leglise|libramont|libramont-chevigny|neufchateau|sainte-ode|vaux-sur-sure)(?:/.*)?$" {
	rewrite ^ http://www.policecentreardenne.be permanent;
}

location ~ "^/(5310|beauraing|bievre|gedinne|houille-semois|vresse-sur-semois)(?:/.*)?$" {
	rewrite ^ http://www.houillesemois.be/ permanent;
}

location ~ "^/(beernem|houtsche|oostkamp|zedelgem)(?:/.*)?$" {
	rewrite ^ /5447 permanent;
}

location ~ "^/(5373|beringen|ham|tessenderlo)(?:/.*)?$" {
	rewrite ^ http://www.politie-bht.be permanent;
}

location ~ "^/(5286|berloz|crisnee|donceel|faimes|fexhe-le-haut-clocher|geer|hesbaye|oreye|remicourt|waremme)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/lie/5286.htm permanent;
}

location ~ "^/(5321|bernissart|peruwelz)(?:/.*)?$" {
	rewrite ^ http://www.dinopol.be permanent;
}

location ~ "^/(5397|bertem|dijleland|huldenberg|oud-heverlee)(?:/.*)?$" {
	rewrite ^ http://www.pzdijleland.be/ permanent;
}

location ~ "^/(5302|bertrix|bouillon|daverdisse|herbeumont|libin|paliseul|saint-hubert|semois-et-lesse|semoisetlesse|tellin|wellin)(?:/.*)?$" {
	rewrite ^ http://www.semoisetlesse.be permanent;
}

location ~ "^/beveren(?:/.*)?$" {
	rewrite ^ /5430 permanent;
}

location ~ "^/(5280|beyne|beyne-heusay|fleron|heusay|soumagne)(?:/.*)?$" {
	rewrite ^ http://www.zp5280-police.be/ permanent;
}

location ~ "^/(5391|bierbeek|boutersem|holsbeek|lubbeek|pzlubbeek)(?:/.*)?$" {
	rewrite ^ http://www.pzlubbeek.be/ permanent;
}

location ~ "^/(bilzen|hoeselt|riemst)(?:/.*)?$" {
	rewrite ^ /5381 permanent;
}

location ~ "^/(5385|bocholt|bree|gruitrode|kinrooi|meeuwen|meeuwen-gruitrode|nol|noordoost-limburg|noordoostlimburg)(?:/.*)?$" {
	rewrite ^ http://users.skynet.be/sb276392 permanent;
}

location ~ "^/(5347|boom|hemiksem|niel|rumst|rupel|schelle)(?:/.*)?$" {
	rewrite ^ http://www.politiezonerupel.be permanent;
}

location ~ "^/(5327|boraine|boussu|colfontaine|frameries|quaregnon|saint-ghislain)(?:/.*)?$" {
	rewrite ^ http://www.policeboraine.be permanent;
}

location ~ "^/(bornem|klein-brabant|puurs|pz-klein-brabant|sint-amands)(?:/.*)?$" {
	rewrite ^ /5356 permanent;
}

location ~ "^/(5273|braine-lalleud)(?:/.*)?$" {
	rewrite ^ http://www.zpbrainelalleud.be permanent;
}

location ~ "^/(5268|braine-le-chateau|ittre|ouest-brabant-wallon|rebecq|tubize)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/bwa/5268.htm permanent;
}

location ~ "^/(5328|braine-le-comte|ecaussinnes|haute-senne|leroeulx|soignies)(?:/.*)?$" {
	rewrite ^ http://www.policehautesenne.be permanent;
}

location ~ "^/(5293|braives|burdinne|hannut|heron|hesbaye-ouest|lincent|wasseiges)(?:/.*)?$" {
	rewrite ^ http://www.police.hesbayeouest.be permanent;
}

location ~ "^/(brasschaat)(?:/.*)?$" {
	rewrite ^ /5352 permanent;
}

location ~ "^/(brecht|malle|schilde|voorkempen|zoersel)(?:/.*)?$" {
	rewrite ^ /5355 permanent;
}

location ~ "^/(5450|bredene|dehaan)(?:/.*)?$" {
	rewrite ^ http://www.politiebredenedehaan.be permanent;
}

location ~ "^/(5326|brugelette|chievres|enghien|jurbise|lens|silly|sylle-et-dendre)(?:/.*)?$" {
	rewrite ^ http://www.policesylleetdendre.be/ permanent;
}

location ~ "^/(brussel|bruxelles|elsene|ixelles|laken|polbru)(?:/.*)?$" {
	rewrite ^ /5339 permanent;
}

location ~ "^/(5344|brussel.zone5|bruxelles.zone5|evere|saint-josse-ten-noode|schaarbeek|schaerbeek|sint-joost-ten-node)(?:/.*)?$" {
	rewrite ^ http://www.polbruno.be permanent;
}

location ~ "^/(buggenhout|lebbeke)(?:/.*)?$" {
	rewrite ^ /5437 permanent;
}

location ~ "^/(5320|celles|estaimpuis|mont-de-lenclus|pecq|val-de-lescaut|valdelescaut)(?:/.*)?$" {
	rewrite ^ http://police.valdelescaut.be/051208114608/index.asp permanent;
}

location ~ "^/(5335|chapelle-lez-herlaimont|manage|mariemont|morlanwelz|seneffe)(?:/.*)?$" {
	rewrite ^ http://www.morlanwelz.be/police/index.htm permanent;
}

location ~ "^/(5270|chastre|court-saint-etienne|mont-saint-guibert|orne-thyle|villers-la-ville|walhain)(?:/.*)?$" {
	rewrite ^ http://www.policeornethyle.be/ permanent;
}

location ~ "^/(5299|chiny|etalle|florenville|gaume|maix-devant-virton|rouvroy|tintigny|virton)(?:/.*)?$" {
	rewrite ^ http://www.policedegaume.be redirect;
}

location ~ "^/(collines|ellezelles|flobecq|frasnes-lez-envaing|lessines)(?:/.*)?$" {
	rewrite ^ /5323 permanent;
}

location ~ "^/(5318|comines|comines-warneton|warneton)(?:/.*)?$" {
	rewrite ^ http://www.policedecomines-warneton.be permanent;
}

location ~ "^/(courcelles|fontaine-leveque|trieux|zone-des-trieux|zonedestrieux)(?:/.*)?$" {
	rewrite ^ /5336 permanent;
}

location ~ "^/(couvin|police3vallees|viroinval)(?:/.*)?$" {
	rewrite ^ /5311 permanent;
}

location ~ "^/(damme|knokke|knokke-heist)(?:/.*)?$" {
	rewrite ^ /5446 permanent;
}

location ~ "^/(deerlijk|gavers|harelbeke)(?:/.*)?$" {
	rewrite ^ /5458 permanent;
}

location ~ "^/(5420|deinze|zulte)(?:/.*)?$" {
	rewrite ^ http://www.politiedeinzezulte.be permanent;
}

location ~ "^/(5443|dendermonde)(?:/.*)?$" {
	rewrite ^ http://www.dendermonde.be/politie/3559/default.aspx?id=2236&rf=1 permanent;
}

location ~ "^/(5454|dentergem|ingelmunster|meulebeke|midow|oostrozebeke|wielsbeke)(?:/.*)?$" {
	rewrite ^ http://www.politiezone-midow.be permanent;
}

location ~ "^/(depinte|gavere|nazareth|schelde-leie|scheldeleie|sint-martens-latem)(?:/.*)?$" {
	rewrite ^ /5419 permanent;
}

location ~ "^/(destelbergen|melle|merelbeke|oosterzele|pz-rhode&schelde|pz-rhode-schelde|pzrhode&schelde|pzrhodeschelde|rhode&schelde|rhode-schelde|rhodeschelde)(?:/.*)?$" {
	rewrite ^ /5418 permanent;
}

location ~ "^/(diepenbeek|hasselt|hazodi|zonhoven)(?:/.*)?$" {
	rewrite ^ /5370 permanent;
}

location ~ "^/(diksmuide|houthulst|koekelare|kortemark|polder|politiezonepolder)(?:/.*)?$" {
	rewrite ^ /5460 permanent;
}

location ~ "^/dilbeek(?:/.*)?$" {
	rewrite ^ /5406 permanent;
}

location ~ "^/(5383|dilsen|dilsen-stokkem|maaseik|maasland|stokkem)(?:/.*)?$" {
	rewrite ^ http://www.politie-maasland.be/ permanent;
}

location ~ "^/(5289|dison|pepinster|verviers|vesdre|zone-vesdre|zonevesdre)(?:/.*)?$" {
	rewrite ^ http://www.policevesdre.be/site/ permanent;
}

location ~ "^/(dour|hauts-pays|hensies|honnelles|quievrain)(?:/.*)?$" {
	rewrite ^ /5329 permanent;
}

location ~ "^/(drogenbos|linkebeek|rhode|rode|rode-rhode|sint-genesius-rode)(?:/.*)?$" {
	rewrite ^ /5403 permanent;
}

location ~ "^/(5300|durbuy|erezee|gouvy|hotton|houffalize|laroche-en-ardenne|manhay|marche-en-famenne|nassonge|rendeux|tenneville|vielsalm)(?:/.*)?$" {
	rewrite ^ http://www.policefamenne-ardenne.be permanent;
}

location ~ "^/(eeklo|kaprijke|meetjesland|meetjesland-centrum|sint-laureins)(?:/.*)?$" {
	rewrite ^ /5417 permanent;
}

location ~ "^/(5306|entre-sambre-et-meuse|floreffe|fosses-la-ville|mettet|profondeville)(?:/.*)?$" {
	rewrite ^ http://www.policeentresambreetmeuse.be/ permanent;
}

location ~ "^/(erpe|erpe-mere|erpemerelede|lede|mere)(?:/.*)?$" {
	rewrite ^ /5441 permanent;
}

location ~ "^/(erquelinnes|estinnes|lermes|lobbes|merbes-le-chateau)(?:/.*)?$" {
	rewrite ^ /5333 permanent;
}

location ~ "^/(5350|essen|grens|kalmthout|wuustwezel)(?:/.*)?$" {
	rewrite ^ http://www.pzgrens.be redirect;
}

location ~ "^/(5343|etterbeek|montgomery|sint-lambrechts-woluwe|sint-pieters-woluwe|woluwe-saint-lambert|woluwe-saint-pierre)(?:/.*)?$" {
	rewrite ^ http://www.policemontgomery.irisnet.be permanent;
}

location ~ "^/(5292|eupen|lacalamine|lontzen|raeren|weser-gohl|weser.gohl|wesergohl)(?:/.*)?$" {
	rewrite ^ http://www.polizei-weser-goehl.be redirect;
}

location ~ "^/(5287|fagnes|jalhay|spa|theux)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/lie/5287.htm permanent;
}

location ~ "^/(flemalle)(?:/.*)?$" {
	rewrite ^ /5282 permanent;
}

location ~ "^/(5309|florennes|flowal|walcourt)(?:/.*)?$" {
	rewrite ^ http://www.flowal.be permanent;
}

location ~ "^/(5366|geel|laakdal|meerhout|politiezonegeel)(?:/.*)?$" {
	rewrite ^ http://www.pzglm.be/ permanent;
}

location ~ "^/(5267|genappe|nivelles)(?:/.*)?$" {
	rewrite ^ http://www.votrepolice.be permanent;
}

location ~ "^/(5338|germinalt|gerpinnes|ham-sur-heure-nalinnes|montigny-le-tilleul|thuin)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/hai/5338.htm permanent;
}

location ~ "^/(5376|gingelom|nieuwerkerken|sint-truiden|sinttruiden)(?:/.*)?$" {
	rewrite ^ http://www.politie-sint-truiden.be redirect;
}

location ~ "^/(gistel|ichtegem|jabbeke|kouter|oudenburg|torhout)(?:/.*)?$" {
	rewrite ^ /5452 permanent;
}

location ~ "^/(grensleie|ledegem|menen|wevelgem)(?:/.*)?$" {
	rewrite ^ /5455 permanent;
}

location ~ "^/(halen|herk-de-stad|lummen|politiewestlimburg|west-limburg|westlimburg)(?:/.*)?$" {
	rewrite ^ /5374 permanent;
}

location ~ "^/halle(?:/.*)?$" {
	rewrite ^ /5413 permanent;
}

location ~ "^/(hamme|waasmunster)(?:/.*)?$" {
	rewrite ^ /5435 permanent;
}

location ~ "^/(hekor|herent|herko|kortenberg)(?:/.*)?$" {
	rewrite ^ /5393 permanent;
}

location ~ "^/(5276|helecine|jodoigne|orp-jauche|perwez|ramillies)(?:/.*)?$" {
	rewrite ^ http://www.zpjodoigne.be/ permanent;
}

location ~ "^/(5279|herstal)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/lie/5279.htm permanent;
}

location ~ "^/(heusden|heusden-zolder|heusdenzolder|zolder)(?:/.*)?$" {
	rewrite ^ /5375 permanent;
}

location ~ "^/(5453|hooglede|izegem|riho|roeselare)(?:/.*)?$" {
	rewrite ^ http://www.politiezoneriho.be permanent;
}

location ~ "^/(hoogstraten|merksplas|noorderkempen|politienoorderkempen|rijkevorsel)(?:/.*)?$" {
	rewrite ^ /5363 permanent;
}

location ~ "^/(5313|houyet|lesse-et-lhomme|rochefort)(?:/.*)?$" {
	rewrite ^ http://www.policehouyetrochefort.be/contenu/police1.asp permanent;
}

location ~ "^/(5295|huy)(?:/.*)?$" {
	rewrite ^ http://www.police.huy.be/ permanent;
}

location ~ "^/(infozone)(?:/.*)?$" {
	rewrite ^ http://www.info-zone.be redirect;
}

location ~ "^/(5308|jemeppe-sur-sambre)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/nam/5308.htm permanent;
}

location ~ "^/(kampenhout|kastze|steenokkerzeel|zemst)(?:/.*)?$" {
	rewrite ^ /5412 permanent;
}

location ~ "^/(5348|kapellen|stabroek)(?:/.*)?$" {
	rewrite ^ http://www.pznoord.be permanent;
}

location ~ "^/(5425|kluisbergen|kruishoutem|oudenaarde|petegem|vlaamse-ardennen|wortegem|wortegem-petegem|zingem)(?:/.*)?$" {
	rewrite ^ http://www.pz-vlaamseardennen.be/ permanent;
}

location ~ "^/(5456|kortrijk|kuurne|lendelede|pzvlas|vlas)(?:/.*)?$" {
	rewrite ^ http://www.pzvlas.be permanent;
}

location ~ "^/(kruibeke|temse)(?:/.*)?$" {
	rewrite ^ /5433 permanent;
}

location ~ "^/(lan|landen|linter|zoutleeuw)(?:/.*)?$" {
	rewrite ^ /5390 permanent;
}

location ~ "^/(5386|lanaken|lama)(?:/.*)?$" {
	rewrite ^ /5853 permanent;
}

location ~ "^/(5277|liege)(?:/.*)?$" {
	rewrite ^ http://www.policeliege.be/ permanent;
}

location ~ "^/(5290|lierneux|malmedy|stavelot|stoumont|trois-ponts|waimes)(?:/.*)?$" {
	rewrite ^ http://www.stavelotmalmedy.be permanent;
}

location ~ "^/(lochristi|moerbeke|puyenbroeck|regiopuyenbroeck|wachtebeke|zelzate)(?:/.*)?$" {
	rewrite ^ /5416 permanent;
}

location ~ "^/lokeren(?:/.*)?$" {
	rewrite ^ /5434 permanent;
}

location ~ "^/(louvain-la-neuve|ottignies)(?:/.*)?$" {
	rewrite ^ /5275 permanent;
}

location ~ "^/(lovendegem|lowazone|nevele|waarschoot|zomergem)(?:/.*)?$" {
	rewrite ^ /5422 permanent;
}

location ~ "^/(5387|maasmechelen)(?:/.*)?$" {
	rewrite ^ http://www.politiemaasmechelen.be permanent;
}

location ~ "^/(5411|machelen|vilvoorde)(?:/.*)?$" {
	rewrite ^ http://www.politie.vima.be permanent;
}

location ~ "^/(5317|mouscron)(?:/.*)?$" {
	rewrite ^ http://www.policemouscron.be/ permanent;
}

location ~ "^/(5303|namur|polnam)(?:/.*)?$" {
	rewrite ^ http://www.polnam.be permanent;
}

location ~ "^/(5278|neupre|seraing)(?:/.*)?$" {
	rewrite ^ http://www.policeweb.be/070523161802/index.asp permanent;
}

location ~ "^/oostende(?:/.*)?$" {
	rewrite ^ /5449 permanent;
}

location ~ "^/(policenet)(?:/.*)?$" {
	rewrite ^ http://www.polnet.be redirect;
}

location ~ "^/(politie.opsporingen.kempen)(?:/.*)?$" {
	rewrite ^ http://users.pandora.be/politie.opsporingen.kempen redirect;
}

location ~ "^/(5404|politiebeersel)(?:/.*)?$" {
	rewrite ^ http://www.politiebeersel.be permanent;
}

location ~ "^/(pzzara|ranst|zandhoven|zara)(?:/.*)?$" {
	rewrite ^ /5354 permanent;
}

location ~ "^/(5427|ronse)(?:/.*)?$" {
	rewrite ^ http://www.ronse.be/algemeen/bestuur/politie/overzicht permanent;
}

location ~ "^/(5307|sambreville|samsom|sombreffe)(?:/.*)?$" {
	rewrite ^ http://www.policesamsom.be/ permanent;
}

location ~ "^/schoten(?:/.*)?$" {
	rewrite ^ /5353 permanent;
}

location ~ "^/SCT(?:/.*)?$" {
	rewrite ^ /sct permanent;
}

location ~ "^/(sint-niklaas|sintniklaas)(?:/.*)?$" {
	rewrite ^ /5432 permanent;
}

location ~ "^/tervuren(?:/.*)?$" {
	rewrite ^ /5398 permanent;
}

location ~ "^/(5382|voeren)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/lim/5382.htm permanent;
}

location ~ "^/(5274|waterloo)(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/bwa/5274.htm permanent;
}

location ~ "^/(5271|wavre)(?:/.*)?$" {
	rewrite ^ http://www.policewavre.be permanent;
}

location ~ "^/(5357|willebroek)(?:/.*)?$" {
	rewrite ^ http://www.politiewillebroek.be/ permanent;
}

location ~ "^/(5346|zwijndrecht)(?:/.*)?$" {
	rewrite ^ http://www.politie.zwijndrecht.be/ permanent;
}

location ~ "^/5403(?:/.*)?$" {
	rewrite ^ http://www.infozone.be/fiches/vbr/5403.htm permanent;
}

location ~ "^/neteland(?:/.*)?$" {
	rewrite ^ /5369 permanent;
}

location ~ "^/(zone|training|demo)(?:/.*)?$" {
	rewrite ^ / redirect;
}

location ~ "^/(5457|anzegem|avelgem|spiere-helkijn|waregem|zwevegem)(?:/.*)?$" {
	rewrite ^ http://www.pzmira.be/ permanent;
}

location ~ "^/(5319|beloeil|leuze-en-hainaut)(?:/.*)?$" {
	rewrite ^ http://www.policebeloeil-leuze.be/ permanent;
}

location ~ "^/(5324|mons|quevy)(?:/.*)?$" {
	rewrite ^ http://www.policemonsquevy.be/ permanent;
}

location ~ "^/(5337|brunau|fleurus)(?:/.*)?$" {
	rewrite ^ http://www.policebrunau.be/ permanent;
}

location ~ "^/csd-dendermonde(?:/.*)?$" {
	rewrite ^ /portal permanent;
}
