load 'deploy'

Dir['config/deploy/extensions/*.rb'].each {|l| require l }

Dir['vendor/gems/*/recipes/*.rb','vendor/plugins/*/recipes/*.rb','config/deploy/recipes/*.rb'].each { |plugin| load(plugin) }

load 'config/deploy'
